### ISSUE TITLE
Repo "https://github.com/GFTN/gftn-web.git" is not found

### ISSUE THREAD

**Issue by ttlpta** [GFTN/gftn-services#1]
I followed the document "Website/Portal for IBM Blockchain WorldWire" to run the portal application locally. But the repo "https://github.com/GFTN/gftn-web.git" is not found. 

Did it change to another repo URL? Or do I need to grant permission to access this repo?

**Comment by chaseoli** [comment]
No, must be a typo. The web portal is in this repo at https://github.com/GFTN/gftn-services/tree/main/world-wire-web (via Angular).

**Comment by ttlpta** [comment]
@chaseoli Thank you for your response. One more thing regarding the document. In step 3 "Obtain VSCode Launch & Task Files for auth-service", I don't see the folder .vscode in auth-service. Can you double-check again?

**Comment by chaseoli** [comment]
Unfortunately, I don't think that was open-sourced by IBM, and I'm no longer at the company. It's probably going to be a pain trying to get that to run without the launch files. @kingaj12 any chance you could sanitize the original launch files and put back into the repo? 

If not, you are best running it and debugging it along the way, via `npm start`  from https://github.com/GFTN/gftn-services/blob/main/auth-service/authentication/package.json. There are several secrets and environment variables that you will need to run it but without the .vscode dir there really is no single clear picture of how to run it.

**Comment by kingaj12** [comment]
Hi @chaseoli!

Sorry didn't see this before.

The .vscode files were probably excluded by .gitignore.  I can put them into this repository after checking for secrets.  

Let me know if there is anything else I can help with.
